exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]

sitename:  Rockola 
tagline: Rockolateka Virtual al Alcanze de tus Digitos

production_url : http://rockola.flujos.org
url: http://rockola.flujos.org

safe:        false
auto:        false
baseurl:    /


future:      false
pygments:    true
markdown:    maruku
permalink:   /blog/:year/:month/:day/:title/

navigation:
- text: Home
  url: /
  layout: default  
- text: About us
  url: /about/
  layout: page  
- text: Blog
  url: /blog/
  layout: archive




