--- 
- merb-core (= 0.9.9, runtime)
- rake (>= 0, runtime)
- thor (>= 0.9.7, runtime)
- merb_datamapper (= 0.9.9, runtime)
- merb-helpers (= 0.9.9, runtime)
- merb-assets (= 0.9.9, runtime)
- merb-action-args (= 0.9.9, runtime)
- merb_has_flash (>= 0, runtime)
- merb-mailer (= 0.9.9, runtime)
- merb-slices (= 0.9.9, runtime)
- merb-auth (= 0.9.9, runtime)
- merb-auth-slice-password (= 0.9.9, runtime)
- merb-auth-core (= 0.9.9, runtime)
- merb-auth-more (= 0.9.9, runtime)
- dm-aggregates (>= 0, runtime)
- dm-validations (>= 0, runtime)
- dm-timestamps (>= 0, runtime)
- merb_paginate (>= 0, runtime)
- dm-core (>= 0, runtime)
